### PR TITLE
Add splashscreen

### PR DESCRIPTION
**Pull request by Lamparter**
## Description

Makes splashscreen not optional

## Related Issues

https://discord.com/channels/714581497222398064/1273778948903403520/1273778948903403520

## Changes Made

- Added uap5 xml schematics to manifest 
- Stated that the splash screen is not optional

## Checklist

- [ ] I have tested these changes thoroughly.
- [x] I have reviewed my code for any potential errors or issues.
- [ ] I have followed the code style guidelines for this project.

## Additional Notes

All of these code changes completed on my phone! 😄

## Code of Conduct

By submitting this issue, I agree to follow the [Code of Conduct](CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by Lamparter** [comment]
@RyanLua please use the squash and merge feature because I would like to get credit for this pr

**Comment by RyanLua** [comment]
I took a look and tried to test it myself, but it still shows black before the UI loads?

image

**Comment by Lamparter** [comment]
> I took a look and tried to test it myself, but it still shows black before the UI loads?

I may have mistyped something - @RyanLua I'm on holiday right now when I get back I'll take a closer look

**Comment by RyanLua** [comment]
@Lamparter Are you still working on this or can I close this stale PR?

**Comment by Lamparter** [comment]
Yeah I don't think I really understand how to add the splashscreen; it's strange because this line of code usually adds it. Perhaps that's only on UWP apps 😅

**Comment by Lamparter** [comment]
This might work: 
```cs
protected override void OnLaunched(LaunchActivatedEventArgs args)
{
    base.OnLaunched(args);

    Frame rootFrame = Window.Current.Content as Frame;

    if (rootFrame == null)
    {
        rootFrame = new Frame();
        rootFrame.NavigationFailed += OnNavigationFailed;
        Window.Current.Content = rootFrame;
    }

    if (rootFrame.Content == null)
    {
        rootFrame.Navigate(typeof(MainPage), args.Arguments);
    }

    Window.Current.Activate();
}
```

**Pull request closed without merging**
